### ISSUE TITLE
Dark Sky API no longer accepting new signups.

### ISSUE THREAD

**Issue by VergeDX** [aleksilassila/uebersicht-fetch#2]
Due to https://darksky.net/dev, dark sky API no longer accepting new signups.  
So is there any plan to switch to any other's service...?

**Comment by aleksilassila** [comment]
Thanks for letting me know, I'll definitely look into alternatives in that case.

**Comment by chrmatique** [comment]
I'm already working on porting the code to use OpenWeatherMaps. 
List of things working so far:
* Weather conditions
* Temperature
* City name

I'm definitely open to adding more data to this if need be, but I merely replaced the Dark Sky data with OWM data. I'm more than willing to open a pull request with these initial changes.

**Comment by aleksilassila** [comment]
Thanks, I'll check it out!

**Comment by chrmatique** [comment]
No problem! 😄

**Comment by chrmatique** [comment]
As an after thought in #3:
The "°F" is rather explicit, I'm actively working to fix this. @aleksilassila I wouldn't pull my PR until I resolve this, thanks! 😄

**Comment by aleksilassila** [comment]
Merged #3
